on:
    pull_request:
        branches: [main, develop]

    workflow_dispatch:

jobs:
    runE2E:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '18.13.x'
            
            - name: build and run backend
              run: cd backend/ws && dotnet run & echo "API_PID=$!" >> $GITHUB_ENV
              env:
                PGCONN: ${{ secrets.PGCONN }}
                JWT_KEY: ${{ secrets.JWT_KEY }}
            
            - name: Install dependencies
              run: cd frontend && npm install

            - name: Start frontend
              run: cd frontend && npm start & echo "FRONTEND_PID=$!" >> $GITHUB_ENV

            - uses: DevExpress/testcafe-action@latest
              with:
                args: "chrome e2e_test/e2e.js"
              env:
                SECRET: ${{ secrets.USERSECRET }}

            - name: Stop backend
              run: kill $API_PID
            
            - name: Stop frontend
              run: kill $FRONTEND_PID